#!/bin/bash

show_help()
{
cat << EOF
usage: $0 options

This script is to update the admin password.

OPTIONS:
   -h|--help|-\?        Show this message
   -o|--old-password    Specify the old password (required)
   -n|--new-password    Specify the new password (required)
EOF
}

# NOTE: This requires GNU getopt.  On Mac OS X and FreeBSD, you have to install this
# separately; see below.
TEMP=`getopt -o o:n: --long old-password:,new-password: -n 'uap' -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

OLDPASS=
NEWPASS=
while true; do
  case "$1" in
    -o | --old-password ) OLDPASS="$2"; shift 2 ;;
    -n | --new-password ) NEWPASS="$2"; shift 2 ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

if [[ -n "$OLDPASS" && -n "$NEWPASS" ]]; then
	UPDATE_PASSWORD_LDIF=updatePassword.ldif
	if [ -f $UPDATE_PASSWORD_LDIF ]; then
		rm $UPDATE_PASSWORD_LDIF
	fi
	touch $UPDATE_PASSWORD_LDIF
	read -r -d '' LDIF_CONTENT <<- EOM
		dn: uid=admin,ou=system
		changetype: modify
		replace: userPassword
		userPassword:$NEWPASS
	EOM
	echo "$LDIF_CONTENT" >> $UPDATE_PASSWORD_LDIF
	ldapmodify -x -h localhost -p 10389 -D "uid=admin,ou=system" -w $OLDPASS -c -f updatePassword.ldif
else
	show_help
fi
